### PR TITLE
Add digilines support to telemosaics

### PR DESCRIPTION
**Pull request by Omikhleia**
This PR is a proposal to add digilines support to the telemosaic:
- digiline signal "telemosaic _playername_ _hashpos_" when the player is teleported. The _hashpos_ argument is the hashed position (in telemosaic sense) for the originating mosaic.
- digiline commands "disable", "enable" and "channel _channelname_". I did not want to add a formspec for setting the channel, as i felt it would lose the simplicity of existing mosaics (but this may be subject to debate!), so the default channel is the empty one ("") and the "channel" command allows to programmaticaly change it. If the channel name is left empty, it is reset to "".

A new node (disabled state, with grayed texture) is added.

One of my test setup, if it may help:

telemosaic_digiline

With LUAC:
```lua
if event.type == "digiline" and event.channel == mem.chan then
  digiline_send("screen",  "["..event.channel .. "] " .. event.msg)
  digiline_send(mem.chan, "disable "..event.msg)
end

if event.type == "on" and event.pin.name == "A" then
 digiline_send(mem.chan, "enable")
end

if event.type == "off" and event.pin.name == "A" then
 digiline_send(mem.chan, "disable")
end

if event.type == "digiline" and event.channel == "keyboard" then
  digiline_send(mem.chan, "channel " .. event.msg)
  mem.chan = event.msg
  digiline_send("screen",  "channel [" .. event.msg.."]")
end

if event.type == "program" then
  mem.chan = ""
end
```

EDIT: My in-game name = Gorlock (FWIW)

### CODE REVIEW

**Review by S-S-X — APPROVED** [review]
Seems good :+1: 
Ping @BuckarooBanzay / @OgelGames if you wanna check too

This will also add 2 new nodes: telemosaic:beacon_disabled and telemosaic:beacon_disabled_protected

**Comment by BuckarooBanzay** [comment]
wow, this looks nice :+1: 

About the digiline-channel: would you mind if that would be hardcoded to "telemosaic" instead of "" (feels kinda weird)?

**EDIT**: what about the message? can it be a table like `{ playername = "", hashpos = "", sourcepos = {}, targetpos = {} }`?
It would make it easier for parsing with a LuaController

**Also, fyi:** i might move that to github.com/mt-mods/, add some code-checks and modularize the code a bit in the future..

**Comment by S-S-X** [comment]
@BuckarooBanzay 

> About the digiline-channel: would you mind if that would be hardcoded to "telemosaic" instead of "" (feels kinda weird)?

I could agree with default being "telemosaic" but ability to change channel is useful if there's many telemosaics close to each other and you want to connect all those together to same digiline network... also defaulting to empty channel was my fault...

**Comment by BuckarooBanzay** [comment]
> I could agree with default being "telemosaic" but ability to change channel is useful if there's many telemosaics close to each other and you want to connect all those together to same digiline network... also defaulting to empty channel was my fault...

This would be nice. Even better if they keep the current "simplicity" (no formspec on punch and rightclick).
Also: multiple telemosaics could be distinguished with the "hashpos" attribute

**Comment by S-S-X** [comment]
hashpos maybe could work but thinking about that I started thinking why these:
https://github.com/pandorabox-io/telemosaic/blob/master/teleport.lua#L5-L17
do not use `minetest.hash_node_position(pos)` and `minetest.get_position_from_hash(hash)`, should they?
Anyhow using hashpos for identification will tie telemosaic into that location and therefore makes it harder to adapt if for example jumping telemosaics will be made possible.

Then another minor note about digiline message contents, would it be better to send table here:
https://github.com/pandorabox-io/telemosaic/blob/master/teleport.lua#L251-L252
it would allow easier future updates too as tables are a lot more flexible than custom encoded string.

>  Even better if they keep the current "simplicity" (no formspec on punch and rightclick).

That already works as digiline channel is updated by special digiline message.

**Comment by BuckarooBanzay** [comment]
> That already works as digiline channel is updated by special digiline message.

Oh, right, i should really read more :facepalm:

**Comment by Omikhleia** [comment]
Hmm that's right, a table is indeed probably more clever for the signal, and also more extensive. Do you want me to make another PR for it?

**Comment by BuckarooBanzay** [comment]
> Hmm that's right, a table is indeed probably more clever for the signal, and also more extensive. Do you want me to make another PR for it?

You should have received an invite for the repository, i believe it will make things easier, we can still make PR's directly on a branch of the repo or on bigger changes if you want.

If there are updates for the mod it will appear on https://github.com/pandorabox-io/pandorabox-mods/pulls within one or two days (i think the dependabot does not "work" on the weekends...)

**Comment by S-S-X** [comment]
@Omikhleia I dropped things from comments to issue #8, yes would be nice if you'd like to drop changes for those.
This digiline support will be very nice addition in the end :+1:

**Pull request merged**
