### PR TITLE
Add ability to teleport on right-click

### PR DESCRIPTION
**Pull request by OgelGames**
Adds settings option to allow teleportation by right-clicking the beacon, instead of automatic teleportation after a short time.

To enable the new functionality "telemosaic_right_click_teleport = true" must be added to minetest.conf, otherwise it will default to automatic teleportation.

Fixes issue: https://github.com/pandorabox-io/pandorabox.io/issues/286

### CODE REVIEW

**Comment by thomasrudin** [comment]
Ooh, that was fast :smile: thx

**Comment by OgelGames** [comment]
Yeah, that's because I had already done some experimenting with it a couple days ago, so basically all I did today was fork the repo, refine my code a bit, and make the PR :smile:

**Comment by thomasrudin** [comment]
@OgelGames i added that on the test-server (`test.pandorabox.io`) rightclick does not seem to work there (haven't tried it in singleplayer though)

**Comment by OgelGames** [comment]
Did you add the required setting as mentioned above? I just tried it on the test-server, and it's still working as normal (automatic teleportation), which is the default when the setting is not added.

**Comment by thomasrudin** [comment]
Oh, i forgot the setting :P sorry...
But now it only works if you stand on the telemosaic and right-click...

I expected it to work if you stand on it *or* right-click on it. :P
Anyways, this looks good nonetheless, i hope you are ok with it when i extend on your feature later :smile:

**Comment by OgelGames** [comment]
> I expected it to work if you stand on it _or_ right-click on it. :P

When I was adding the right-click I was thinking it was more to prevent getting teleported accidentally (which has happened to me more than a few times), as well preventing getting stuck teleporting because of lag, but now you mention it, not having to stand on it would make more sense...

I'll see what I can do tomorrow, and will make another PR if I find a way to change it :wink: 

> i hope you are ok with it when i extend on your feature later

Of course :smile:

**Comment by OgelGames** [comment]
Done: https://github.com/pandorabox-io/telemosaic/pull/2

Actually much simpler to do than I thought, only a few extra lines of code 😄

**Pull request merged**
